apiVersion: apps/v1
kind: Deployment               
metadata:
  name: ridecell       
spec:
  replicas: 1                
  selector:
    matchLabels:
      app: ridecell       
  template:                    
    metadata:
      labels:                    
        app: ridecell 
    spec:                      
      containers:
      - name: ridecell
        image: saiki8/ridecellci:latest
        imagePullPolicy: IfNotPresent