name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        USER: ${{secrets.DOCKERHUB_USERNAME}}
        TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
      run: |
        docker login -u $USER -p $TOKEN
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ridecellimage:latest
    - name: Pushing to Docker Hub
      run: docker push saiki8/ridecellimage
